NoticedError: remove defunct request.uri feature
[1fcfbdd2f7970b68182895c5c792a8c288a01b53](https://github.com/newrelic/newrelic-ruby-agent/commit/1fcfbdd2f7970b68182895c5c792a8c288a01b53)
introduced some custom logic to `NoticedError` to treat the request URI
in a special manner.

[9f7636e5072db0c5d63257be59ec4701e16348de](https://github.com/newrelic/newrelic-ruby-agent/commit/9f7636e5072db0c5d63257be59ec4701e16348de)
removed this custom logic, but did not do enough clean up. A comment and
a code block remained that will no longer effect the noticed error's
agent attributes hash.

Removed the defunct code.